CREATE TABLE `PAY_DETAIL` (
  `ID` INT NOT NULL AUTO_INCREMENT COMMENT '自动ID',
  `OPEN_ID` VARCHAR(100) NOT NULL COMMENT '支付用户OPEN_ID',
  `TOTAL_FEE` INT(8) NOT NULL DEFAULT 0 COMMENT '支付金额(分)',
  `TRANSACTION_ID` VARCHAR(100) NOT NULL COMMENT '支付流水号(平台生成)',
  `TRADE_NUMBER` VARCHAR(100) NOT NULL COMMENT '业务订单号(NAMI生成)',
  `PAY_TIME` DATETIME NOT NULL COMMENT '支付时间',
  PRIMARY KEY (`ID`)  COMMENT '')
COMMENT = '支付明细表';

CREATE TABLE `PAY_USER` (
  `OPEN_ID` VARCHAR(100) NOT NULL COMMENT 'OPEN_ID',
  `NICK_NAME` VARCHAR(100) NOT NULL COMMENT '昵称',
  `AVATAR_URL` VARCHAR(500) NOT NULL COMMENT '头像',
  `UPDATE_TIME` DATETIME NOT NULL COMMENT '更新时间',
  PRIMARY KEY (`OPEN_ID`)  COMMENT '')
DEFAULT CHARACTER SET = utf8mb4
COMMENT = '支付用户表';
